// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const updateHero = `-- name: UpdateHero :exec
UPDATE hero
  set name = $2
WHERE id = $1
`

type UpdateHeroParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateHero(ctx context.Context, arg UpdateHeroParams) error {
	_, err := q.db.Exec(ctx, updateHero, arg.ID, arg.Name)
	return err
}
