version: "3.9"
services:

  db:
    image: postgres:14
    environment:
      #POSTGRES_USER: super
      POSTGRES_PASSWORD: super123
      POSTGRES_DB: super
      TZ: America/Asuncion
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./backend/database/:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

  backend:
    build: backend
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:super123@db:5432/super"
      TZ: America/Asuncion
    # Let's not expose our backend port outside the docker network
    #ports:
    #- "5001:5000"
    networks:
      - backend
      - frontend
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./uploaded_files:/usr/src/app/static/uploaded_files

  
  frontend:
    build: frontend
    environment:
      TZ: America/Asuncion
      BACKEND_URL: http://192.168.100.16:9001/api
    # Port 9000 mapped to the web server to avoid conflicts with the host's
    # nginx with the certbot configuration
    ports:
      - "9001:80"
    networks:
      - frontend
    depends_on:
      - backend
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./bin/40-process-envars.sh:/docker-entrypoint.d/40-process-envars.sh:ro"

networks:
  frontend:
  backend:
